sonar.projectKey=medusa-monorepo
sonar.projectName=Medusa
sonar.sources=packages/medusa/src
sonar.host.url=http://localhost:9001
sonar.token=sqp_a59670e7a4d29abdb68d5fb053db2624fe738fa5
sonar.javascript.lcov.reportPaths=packages/medusa/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/build/**,**/*.spec.ts,**/*.test.ts,**/coverage/**,**/__tests__/**,**/__fixtures__/**,**/medusa-test-utils/**,**/.scannerwork/**,**/.sonar/**
